### ISSUE TITLE
Add support for swapped and inverted axes.

### ISSUE THREAD

**Issue by BroMarduk** [nift4/pigame#15]
Add parameter to the initialization to support swapped and inverted axes.  There are times when other software would require a display to be configured in a non-standard manner and adding these parameters would give a way to allow pigame to run in these configurations.

**Comment by nift4** [comment]
I'm working on this...

**Comment by nift4** [comment]
Working as excepted?

**Comment by nift4** [comment]
In 3d930d6

**Comment by nift4** [comment]
And b734b19

**Comment by nift4** [comment]
And 3a7795e9

**Comment by BroMarduk** [comment]
I think the parameters are swapXY (or swapAxes), invertX, invertY.

Swap X axis with Y axis is a single operation and would be done when the event queue is parsed into the event.   Invert X axis and Invert Y are independent and would be done when we calculate the position.

The naming goes along with what I have seen in the Adafruit and other screen dtoverlays

https://github.com/adafruit/Adafruit-PiTFT-Helper/blob/master/adafruit-pitft-helper

**Comment by nift4** [comment]
Oops, my fail :)

**Comment by nift4** [comment]
Finished, but must I swap and invert rel? I think so but I'm not sure.

**Comment by nift4** [comment]
Hello? @BroMarduk

**Comment by gmeader** [comment]
If I set invertx=True , then x is always returned as 0

For example in sdl.py in Raspberry-Pi-Testing, changing 
pitft = pigame.PiTft()
to
pitft = pigame.PiTft(invertx = True)
causes x to always be returned as zero by pygame.mouse.get_pos()

**# To invert x, you need to subtract x from the screen_width**
screen_width, screen_height = pygame.display.get_surface().get_size()
x = screen_width - x

**Comment by gmeader** [comment]
I got sdl.py in Raspberry-Pi-Testing working for my PiTFT 320x240 (EDIT by nift4: 2.8") capacitive by changing pigame.py:
1. implementing a proper swapxy using a temp_x variable to hold the x value while it is being overwritten by the y value.
2. implementing rotation=0 (do nothing)

**Comment by nift4** [comment]
Oops, I'm banana :/

**Comment by nift4** [comment]
I hope it works now, I think swapxy works because it's readed before writing (Python first builds the dictoniary and least but not last it assigns it to the variable)

**Comment by nift4** [comment]
@gmeader Please post details about your workaround in #17

**Comment by nift4** [comment]
Tested it, works
