### ISSUE TITLE
Workaround Discuss: gmeader

### ISSUE THREAD

**Issue by nift4** [nift4/pigame#17]
Workaroud Discussion with @gmeader
EDIT: Finished.

**Comment by gmeader** [comment]
Here is the code I have fixed and/or enhanced. Sorry I did not do a fork and pull request. Next time I will do that.

test.py - I added print statements so you can see what it's doing.
pigame.py - I fixed the swapxy and added the rotation == 0 code
sdl.py - lots of UI changes and a DEBUG flag that displays lots of info if set to True (but disabled the GPIO actions)

[Raspberry-Pi-Testing-glenn.zip](https://github.com/pigamedrv/pigame/files/2848579/Raspberry-Pi-Testing-glenn.zip)

All this works correctly on my PiTFT 2.8 capacitive display.

I still cannot get sdlkit.py to work - see issue in Raspberry-Pi-Testing for details on the error I get.

**Comment by nift4** [comment]
What is your display rotation?

**Comment by nift4** [comment]
I fixed pigameui and tested EVERYTHING in pigame and the working version is now online.

**Comment by nift4** [comment]
I close this issue, but keep looking in.

**Comment by nift4** [comment]
Because this a Discussion for #18

**Comment by nift4** [comment]
@gmeader

**Comment by nift4** [comment]
Finished.
